# Generated by Django 4.0 on 2021-12-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_dept',
        ),
        migrations.AddField(
            model_name='department',
            name='stu_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_app.student'),
        ),
    ]
