# Generated by Django 4.0 on 2021-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0002_remove_student_stu_dept_department_stu_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_id',
            field=models.IntegerField(unique=True),
        ),
    ]
