# Generated by Django 4.0 on 2021-12-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0003_alter_department_dept_id_alter_student_stu_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ManyToManyField(null=True, to='stu_app.Department')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_app.student')),
            ],
        ),
    ]
