# Generated by Django 4.0 on 2021-12-16 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_app', '0004_stu_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_dep',
            name='department',
        ),
        migrations.AddField(
            model_name='stu_dep',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stu_app.department'),
        ),
    ]
